name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/*.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: success()

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: success()

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: success()
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: success()
        with:
          context: .
          push: true
          tags: |
            zhangsean/php:latest
